// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: CrowdCountAPI.proto

#include "CrowdCountAPI.pb.h"
#include "CrowdCountAPI.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace crowdcount {

static const char* CrowdCountAPI_method_names[] = {
  "/crowdcount.CrowdCountAPI/crowdCount",
};

std::unique_ptr< CrowdCountAPI::Stub> CrowdCountAPI::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CrowdCountAPI::Stub> stub(new CrowdCountAPI::Stub(channel));
  return stub;
}

CrowdCountAPI::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_crowdCount_(CrowdCountAPI_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CrowdCountAPI::Stub::crowdCount(::grpc::ClientContext* context, const ::crowdcount::crowdCountRequest& request, ::crowdcount::crowdCountResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_crowdCount_, context, request, response);
}

void CrowdCountAPI::Stub::experimental_async::crowdCount(::grpc::ClientContext* context, const ::crowdcount::crowdCountRequest* request, ::crowdcount::crowdCountResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_crowdCount_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::crowdcount::crowdCountResponse>* CrowdCountAPI::Stub::AsynccrowdCountRaw(::grpc::ClientContext* context, const ::crowdcount::crowdCountRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::crowdcount::crowdCountResponse>::Create(channel_.get(), cq, rpcmethod_crowdCount_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::crowdcount::crowdCountResponse>* CrowdCountAPI::Stub::PrepareAsynccrowdCountRaw(::grpc::ClientContext* context, const ::crowdcount::crowdCountRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::crowdcount::crowdCountResponse>::Create(channel_.get(), cq, rpcmethod_crowdCount_, context, request, false);
}

CrowdCountAPI::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CrowdCountAPI_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CrowdCountAPI::Service, ::crowdcount::crowdCountRequest, ::crowdcount::crowdCountResponse>(
          std::mem_fn(&CrowdCountAPI::Service::crowdCount), this)));
}

CrowdCountAPI::Service::~Service() {
}

::grpc::Status CrowdCountAPI::Service::crowdCount(::grpc::ServerContext* context, const ::crowdcount::crowdCountRequest* request, ::crowdcount::crowdCountResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace crowdcount

