// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: CrowdCountAPI.proto
#ifndef GRPC_CrowdCountAPI_2eproto__INCLUDED
#define GRPC_CrowdCountAPI_2eproto__INCLUDED

#include "CrowdCountAPI.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace crowdcount {

class CrowdCountAPI final {
 public:
  static constexpr char const* service_full_name() {
    return "crowdcount.CrowdCountAPI";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status crowdCount(::grpc::ClientContext* context, const ::crowdcount::crowdCountRequest& request, ::crowdcount::crowdCountResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::crowdcount::crowdCountResponse>> AsynccrowdCount(::grpc::ClientContext* context, const ::crowdcount::crowdCountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::crowdcount::crowdCountResponse>>(AsynccrowdCountRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::crowdcount::crowdCountResponse>> PrepareAsynccrowdCount(::grpc::ClientContext* context, const ::crowdcount::crowdCountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::crowdcount::crowdCountResponse>>(PrepareAsynccrowdCountRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void crowdCount(::grpc::ClientContext* context, const ::crowdcount::crowdCountRequest* request, ::crowdcount::crowdCountResponse* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::crowdcount::crowdCountResponse>* AsynccrowdCountRaw(::grpc::ClientContext* context, const ::crowdcount::crowdCountRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::crowdcount::crowdCountResponse>* PrepareAsynccrowdCountRaw(::grpc::ClientContext* context, const ::crowdcount::crowdCountRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status crowdCount(::grpc::ClientContext* context, const ::crowdcount::crowdCountRequest& request, ::crowdcount::crowdCountResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::crowdcount::crowdCountResponse>> AsynccrowdCount(::grpc::ClientContext* context, const ::crowdcount::crowdCountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::crowdcount::crowdCountResponse>>(AsynccrowdCountRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::crowdcount::crowdCountResponse>> PrepareAsynccrowdCount(::grpc::ClientContext* context, const ::crowdcount::crowdCountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::crowdcount::crowdCountResponse>>(PrepareAsynccrowdCountRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void crowdCount(::grpc::ClientContext* context, const ::crowdcount::crowdCountRequest* request, ::crowdcount::crowdCountResponse* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::crowdcount::crowdCountResponse>* AsynccrowdCountRaw(::grpc::ClientContext* context, const ::crowdcount::crowdCountRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::crowdcount::crowdCountResponse>* PrepareAsynccrowdCountRaw(::grpc::ClientContext* context, const ::crowdcount::crowdCountRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_crowdCount_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status crowdCount(::grpc::ServerContext* context, const ::crowdcount::crowdCountRequest* request, ::crowdcount::crowdCountResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_crowdCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_crowdCount() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_crowdCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status crowdCount(::grpc::ServerContext* context, const ::crowdcount::crowdCountRequest* request, ::crowdcount::crowdCountResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcrowdCount(::grpc::ServerContext* context, ::crowdcount::crowdCountRequest* request, ::grpc::ServerAsyncResponseWriter< ::crowdcount::crowdCountResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_crowdCount<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_crowdCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_crowdCount() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ExperimentalWithCallbackMethod_crowdCount<BaseClass>, ::crowdcount::crowdCountRequest, ::crowdcount::crowdCountResponse>(
          [this](::grpc::ServerContext* context,
                 const ::crowdcount::crowdCountRequest* request,
                 ::crowdcount::crowdCountResponse* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->crowdCount(context, request, response, controller);
                 }, this));
    }
    ~ExperimentalWithCallbackMethod_crowdCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status crowdCount(::grpc::ServerContext* context, const ::crowdcount::crowdCountRequest* request, ::crowdcount::crowdCountResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void crowdCount(::grpc::ServerContext* context, const ::crowdcount::crowdCountRequest* request, ::crowdcount::crowdCountResponse* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_crowdCount<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_crowdCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_crowdCount() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_crowdCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status crowdCount(::grpc::ServerContext* context, const ::crowdcount::crowdCountRequest* request, ::crowdcount::crowdCountResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_crowdCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_crowdCount() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_crowdCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status crowdCount(::grpc::ServerContext* context, const ::crowdcount::crowdCountRequest* request, ::crowdcount::crowdCountResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcrowdCount(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_crowdCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_crowdCount() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ExperimentalWithRawCallbackMethod_crowdCount<BaseClass>, ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->crowdCount(context, request, response, controller);
                 }, this));
    }
    ~ExperimentalWithRawCallbackMethod_crowdCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status crowdCount(::grpc::ServerContext* context, const ::crowdcount::crowdCountRequest* request, ::crowdcount::crowdCountResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void crowdCount(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_crowdCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_crowdCount() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::crowdcount::crowdCountRequest, ::crowdcount::crowdCountResponse>(std::bind(&WithStreamedUnaryMethod_crowdCount<BaseClass>::StreamedcrowdCount, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_crowdCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status crowdCount(::grpc::ServerContext* context, const ::crowdcount::crowdCountRequest* request, ::crowdcount::crowdCountResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedcrowdCount(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::crowdcount::crowdCountRequest,::crowdcount::crowdCountResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_crowdCount<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_crowdCount<Service > StreamedService;
};

}  // namespace crowdcount


#endif  // GRPC_CrowdCountAPI_2eproto__INCLUDED
