// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: FaceEmogDetectAPI.proto
#ifndef GRPC_FaceEmogDetectAPI_2eproto__INCLUDED
#define GRPC_FaceEmogDetectAPI_2eproto__INCLUDED

#include "FaceEmogDetectAPI.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace faceemodetect {

class FaceEmogDetectAPI final {
 public:
  static constexpr char const* service_full_name() {
    return "faceemodetect.FaceEmogDetectAPI";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status faceEmogDetect(::grpc::ClientContext* context, const ::faceemodetect::faceEmogDetectRequest& request, ::faceemodetect::faceEmogDetectResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::faceemodetect::faceEmogDetectResponse>> AsyncfaceEmogDetect(::grpc::ClientContext* context, const ::faceemodetect::faceEmogDetectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::faceemodetect::faceEmogDetectResponse>>(AsyncfaceEmogDetectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::faceemodetect::faceEmogDetectResponse>> PrepareAsyncfaceEmogDetect(::grpc::ClientContext* context, const ::faceemodetect::faceEmogDetectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::faceemodetect::faceEmogDetectResponse>>(PrepareAsyncfaceEmogDetectRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void faceEmogDetect(::grpc::ClientContext* context, const ::faceemodetect::faceEmogDetectRequest* request, ::faceemodetect::faceEmogDetectResponse* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::faceemodetect::faceEmogDetectResponse>* AsyncfaceEmogDetectRaw(::grpc::ClientContext* context, const ::faceemodetect::faceEmogDetectRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::faceemodetect::faceEmogDetectResponse>* PrepareAsyncfaceEmogDetectRaw(::grpc::ClientContext* context, const ::faceemodetect::faceEmogDetectRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status faceEmogDetect(::grpc::ClientContext* context, const ::faceemodetect::faceEmogDetectRequest& request, ::faceemodetect::faceEmogDetectResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::faceemodetect::faceEmogDetectResponse>> AsyncfaceEmogDetect(::grpc::ClientContext* context, const ::faceemodetect::faceEmogDetectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::faceemodetect::faceEmogDetectResponse>>(AsyncfaceEmogDetectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::faceemodetect::faceEmogDetectResponse>> PrepareAsyncfaceEmogDetect(::grpc::ClientContext* context, const ::faceemodetect::faceEmogDetectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::faceemodetect::faceEmogDetectResponse>>(PrepareAsyncfaceEmogDetectRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void faceEmogDetect(::grpc::ClientContext* context, const ::faceemodetect::faceEmogDetectRequest* request, ::faceemodetect::faceEmogDetectResponse* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::faceemodetect::faceEmogDetectResponse>* AsyncfaceEmogDetectRaw(::grpc::ClientContext* context, const ::faceemodetect::faceEmogDetectRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::faceemodetect::faceEmogDetectResponse>* PrepareAsyncfaceEmogDetectRaw(::grpc::ClientContext* context, const ::faceemodetect::faceEmogDetectRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_faceEmogDetect_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status faceEmogDetect(::grpc::ServerContext* context, const ::faceemodetect::faceEmogDetectRequest* request, ::faceemodetect::faceEmogDetectResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_faceEmogDetect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_faceEmogDetect() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_faceEmogDetect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status faceEmogDetect(::grpc::ServerContext* context, const ::faceemodetect::faceEmogDetectRequest* request, ::faceemodetect::faceEmogDetectResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestfaceEmogDetect(::grpc::ServerContext* context, ::faceemodetect::faceEmogDetectRequest* request, ::grpc::ServerAsyncResponseWriter< ::faceemodetect::faceEmogDetectResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_faceEmogDetect<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_faceEmogDetect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_faceEmogDetect() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ExperimentalWithCallbackMethod_faceEmogDetect<BaseClass>, ::faceemodetect::faceEmogDetectRequest, ::faceemodetect::faceEmogDetectResponse>(
          [this](::grpc::ServerContext* context,
                 const ::faceemodetect::faceEmogDetectRequest* request,
                 ::faceemodetect::faceEmogDetectResponse* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->faceEmogDetect(context, request, response, controller);
                 }, this));
    }
    ~ExperimentalWithCallbackMethod_faceEmogDetect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status faceEmogDetect(::grpc::ServerContext* context, const ::faceemodetect::faceEmogDetectRequest* request, ::faceemodetect::faceEmogDetectResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void faceEmogDetect(::grpc::ServerContext* context, const ::faceemodetect::faceEmogDetectRequest* request, ::faceemodetect::faceEmogDetectResponse* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_faceEmogDetect<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_faceEmogDetect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_faceEmogDetect() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_faceEmogDetect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status faceEmogDetect(::grpc::ServerContext* context, const ::faceemodetect::faceEmogDetectRequest* request, ::faceemodetect::faceEmogDetectResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_faceEmogDetect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_faceEmogDetect() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_faceEmogDetect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status faceEmogDetect(::grpc::ServerContext* context, const ::faceemodetect::faceEmogDetectRequest* request, ::faceemodetect::faceEmogDetectResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestfaceEmogDetect(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_faceEmogDetect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_faceEmogDetect() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ExperimentalWithRawCallbackMethod_faceEmogDetect<BaseClass>, ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->faceEmogDetect(context, request, response, controller);
                 }, this));
    }
    ~ExperimentalWithRawCallbackMethod_faceEmogDetect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status faceEmogDetect(::grpc::ServerContext* context, const ::faceemodetect::faceEmogDetectRequest* request, ::faceemodetect::faceEmogDetectResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void faceEmogDetect(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_faceEmogDetect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_faceEmogDetect() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::faceemodetect::faceEmogDetectRequest, ::faceemodetect::faceEmogDetectResponse>(std::bind(&WithStreamedUnaryMethod_faceEmogDetect<BaseClass>::StreamedfaceEmogDetect, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_faceEmogDetect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status faceEmogDetect(::grpc::ServerContext* context, const ::faceemodetect::faceEmogDetectRequest* request, ::faceemodetect::faceEmogDetectResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedfaceEmogDetect(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::faceemodetect::faceEmogDetectRequest,::faceemodetect::faceEmogDetectResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_faceEmogDetect<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_faceEmogDetect<Service > StreamedService;
};

}  // namespace faceemodetect


#endif  // GRPC_FaceEmogDetectAPI_2eproto__INCLUDED
